name: neighbour
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=25.0
  - python=3.10.16
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - appnope==0.1.4
    - asttokens==3.0.0
    - comm==0.2.2
    - contourpy==1.3.1
    - cycler==0.12.1
    - debugpy==1.8.12
    - decorator==5.1.1
    - et-xmlfile==2.0.0
    - exceptiongroup==1.2.2
    - executing==2.2.0
    - filelock==3.17.0
    - fonttools==4.55.8
    - fsspec==2024.12.0
    - ipykernel==6.29.5
    - ipython==8.31.0
    - jedi==0.19.2
    - jinja2==3.1.5
    - joblib==1.4.2
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - kiwisolver==1.4.8
    - markupsafe==3.0.2
    - matplotlib==3.10.0
    - matplotlib-inline==0.1.7
    - mpmath==1.3.0
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - numpy==1.26.4
    - openpyxl==3.1.5
    - packaging==24.2
    - pandas==2.2.3
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==11.1.0
    - platformdirs==4.3.6
    - prompt-toolkit==3.0.50
    - psutil==6.1.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyaml==25.1.0
    - pygments==2.19.1
    - pyparsing==3.2.1
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - rdkit==2024.9.4
    - scikit-learn==1.6.1
    - scikit-learn-extra==0.3.0
    - scikit-optimize==0.10.2
    - scipy==1.15.1
    - seaborn==0.13.2
    - six==1.17.0
    - stack-data==0.6.3
    - sympy==1.13.3
    - threadpoolctl==3.5.0
    - torch==2.2.2
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - typing-extensions==4.12.2
    - tzdata==2025.1
    - wcwidth==0.2.13
prefix: /Users/isaiahbetinol/opt/anaconda3/envs/neighbour
